spring:
  application:
    name: service-location-service
  data:
    mongodb:
#      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/test}
      uri: mongo://root:bitnami@10.193.145.103:27017/test
  
