spring:
  application:
    name: service-location-service
  data:
    mongodb:
#      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/test}
       uri: mongodb://10.193.145.103/test
       username: root
       password: bitnami
